[package]
name = "matrix-dapnet-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "3.1", features = ["derive", "env"] }
dapnet-api = "0.1.1"
env_logger = "0.9"
itertools = "0.10"
log = "0.4"
matrix-sdk = { version = "0.4", default-features = false, features = ["encryption", "markdown", "native-tls"] }
serde = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
